# Generated by Django 5.0.3 on 2024-04-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='photo',
            field=models.ImageField(default='/photo_exercises/barbell-deadlifts.png', upload_to='photo_exercises/%Y/%m/%d/'),
        ),
    ]
